### PR TITLE
asserts

### PR DESCRIPTION
**Pull request by iArnold**

### CODE REVIEW

**Comment by iArnold** [comment]
This is one of those moments git or github lost me again. Such a simple patch how does one get it through to the desired place the metaeducation/renc github repo?

**Comment by giuliolunati** [comment]
You must send a PR to metaeducation

**Comment by giuliolunati** [comment]
But you committed change when r3n was not up-to-date with metaeducation... let me fix that...

**Comment by giuliolunati** [comment]
Done. I had to force a push to r3n/ren-c, so you maybe need to rewind your local repo before to pull from here...

**Pull request merged**
